apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: inferencejobs.fabianoyoschitaki.io #like spec.names.plural
spec:
  group: fabianoyoschitaki.io
  version: v1alpha1
  names:
    kind: InferenceJob
    plural: inferencejobs
  scope: Namespaced
  subresources:
    status: {}
