apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.fabianoyoschitaki.io
spec:
  group: fabianoyoschitaki.io
  version: v1alpha1
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
