apiVersion: fabianoyoschitaki.io/v1alpha1
kind: Job
metadata:
  # name of jobs.fabianoyoschitaki.io
  name: example-job-metadata-busybox
spec:
  # name of the deployment
  deploymentName: example-job-spec-deployment-busybox
  replicas: 1
  imageToDeploy: busybox